[2024-12-09T14:05:15.720+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-09T14:05:15.745+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sparking_flow.python_job manual__2024-12-09T14:05:12.986891+00:00 [queued]>
[2024-12-09T14:05:15.756+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sparking_flow.python_job manual__2024-12-09T14:05:12.986891+00:00 [queued]>
[2024-12-09T14:05:15.757+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2024-12-09T14:05:15.773+0000] {taskinstance.py:2889} INFO - Executing <Task(SparkSubmitOperator): python_job> on 2024-12-09 14:05:12.986891+00:00
[2024-12-09T14:05:15.791+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=695) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-12-09T14:05:15.792+0000] {standard_task_runner.py:72} INFO - Started process 697 to run task
[2024-12-09T14:05:15.791+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'sparking_flow', 'python_job', 'manual__2024-12-09T14:05:12.986891+00:00', '--job-id', '484', '--raw', '--subdir', 'DAGS_FOLDER/spark_***.py', '--cfg-path', '/tmp/tmpnus2a_g9']
[2024-12-09T14:05:15.794+0000] {standard_task_runner.py:105} INFO - Job 484: Subtask python_job
[2024-12-09T14:05:15.874+0000] {task_command.py:467} INFO - Running <TaskInstance: sparking_flow.python_job manual__2024-12-09T14:05:12.986891+00:00 [running]> on host 2a892a3469ec
[2024-12-09T14:05:16.002+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Yusuf Ganiyu' AIRFLOW_CTX_DAG_ID='sparking_flow' AIRFLOW_CTX_TASK_ID='python_job' AIRFLOW_CTX_EXECUTION_DATE='2024-12-09T14:05:12.986891+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-09T14:05:12.986891+00:00'
[2024-12-09T14:05:16.003+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-09T14:05:16.040+0000] {base.py:84} INFO - Retrieving connection 'spark-conn'
[2024-12-09T14:05:16.042+0000] {spark_submit.py:473} INFO - Spark-Submit cmd: spark-submit --master spark://sparkingflow-spark-master-1:7077 --name arrow-spark --deploy-mode client jobs/python/wordcountjob.py
[2024-12-09T14:05:21.716+0000] {spark_submit.py:634} INFO - 24/12/09 14:05:21 INFO SparkContext: Running Spark version 3.5.3
[2024-12-09T14:05:21.733+0000] {spark_submit.py:634} INFO - 24/12/09 14:05:21 INFO SparkContext: OS info Linux, 6.10.14-linuxkit, aarch64
[2024-12-09T14:05:21.734+0000] {spark_submit.py:634} INFO - 24/12/09 14:05:21 INFO SparkContext: Java version 17.0.13
[2024-12-09T14:05:21.906+0000] {spark_submit.py:634} INFO - 24/12/09 14:05:21 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2024-12-09T14:05:22.190+0000] {spark_submit.py:634} INFO - 24/12/09 14:05:22 INFO ResourceUtils: ==============================================================
[2024-12-09T14:05:22.195+0000] {spark_submit.py:634} INFO - 24/12/09 14:05:22 INFO ResourceUtils: No custom resources configured for spark.driver.
[2024-12-09T14:05:22.197+0000] {spark_submit.py:634} INFO - 24/12/09 14:05:22 INFO ResourceUtils: ==============================================================
[2024-12-09T14:05:22.199+0000] {spark_submit.py:634} INFO - 24/12/09 14:05:22 INFO SparkContext: Submitted application: CSVReadExample
[2024-12-09T14:05:22.252+0000] {spark_submit.py:634} INFO - 24/12/09 14:05:22 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2024-12-09T14:05:22.274+0000] {spark_submit.py:634} INFO - 24/12/09 14:05:22 INFO ResourceProfile: Limiting resource is cpu
[2024-12-09T14:05:22.277+0000] {spark_submit.py:634} INFO - 24/12/09 14:05:22 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2024-12-09T14:05:22.395+0000] {spark_submit.py:634} INFO - 24/12/09 14:05:22 INFO SecurityManager: Changing view acls to: ***
[2024-12-09T14:05:22.398+0000] {spark_submit.py:634} INFO - 24/12/09 14:05:22 INFO SecurityManager: Changing modify acls to: ***
[2024-12-09T14:05:22.402+0000] {spark_submit.py:634} INFO - 24/12/09 14:05:22 INFO SecurityManager: Changing view acls groups to:
[2024-12-09T14:05:22.403+0000] {spark_submit.py:634} INFO - 24/12/09 14:05:22 INFO SecurityManager: Changing modify acls groups to:
[2024-12-09T14:05:22.407+0000] {spark_submit.py:634} INFO - 24/12/09 14:05:22 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: ***; groups with view permissions: EMPTY; users with modify permissions: ***; groups with modify permissions: EMPTY
[2024-12-09T14:05:22.965+0000] {spark_submit.py:634} INFO - 24/12/09 14:05:22 INFO Utils: Successfully started service 'sparkDriver' on port 43433.
[2024-12-09T14:05:23.041+0000] {spark_submit.py:634} INFO - 24/12/09 14:05:23 INFO SparkEnv: Registering MapOutputTracker
[2024-12-09T14:05:23.109+0000] {spark_submit.py:634} INFO - 24/12/09 14:05:23 INFO SparkEnv: Registering BlockManagerMaster
[2024-12-09T14:05:23.155+0000] {spark_submit.py:634} INFO - 24/12/09 14:05:23 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2024-12-09T14:05:23.156+0000] {spark_submit.py:634} INFO - 24/12/09 14:05:23 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2024-12-09T14:05:23.162+0000] {spark_submit.py:634} INFO - 24/12/09 14:05:23 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2024-12-09T14:05:23.198+0000] {spark_submit.py:634} INFO - 24/12/09 14:05:23 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-95ed7cd3-606f-413d-a759-9952e521cbdd
[2024-12-09T14:05:23.225+0000] {spark_submit.py:634} INFO - 24/12/09 14:05:23 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2024-12-09T14:05:23.266+0000] {spark_submit.py:634} INFO - 24/12/09 14:05:23 INFO SparkEnv: Registering OutputCommitCoordinator
[2024-12-09T14:05:23.570+0000] {spark_submit.py:634} INFO - 24/12/09 14:05:23 INFO JettyUtils: Start Jetty 0.0.0.0:4040 for SparkUI
[2024-12-09T14:05:23.674+0000] {spark_submit.py:634} INFO - 24/12/09 14:05:23 WARN Utils: Service 'SparkUI' could not bind on port 4040. Attempting port 4041.
[2024-12-09T14:05:23.675+0000] {spark_submit.py:634} INFO - 24/12/09 14:05:23 WARN Utils: Service 'SparkUI' could not bind on port 4041. Attempting port 4042.
[2024-12-09T14:05:23.696+0000] {spark_submit.py:634} INFO - 24/12/09 14:05:23 INFO Utils: Successfully started service 'SparkUI' on port 4042.
[2024-12-09T14:05:24.091+0000] {spark_submit.py:634} INFO - 24/12/09 14:05:24 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://sparkingflow-spark-master-1:7077...
[2024-12-09T14:05:24.411+0000] {spark_submit.py:634} INFO - 24/12/09 14:05:24 INFO TransportClientFactory: Successfully created connection to sparkingflow-spark-master-1/172.18.0.5:7077 after 201 ms (0 ms spent in bootstraps)
[2024-12-09T14:05:24.888+0000] {spark_submit.py:634} INFO - 24/12/09 14:05:24 INFO StandaloneSchedulerBackend: Connected to Spark cluster with app ID app-20241209140524-0001
[2024-12-09T14:05:24.915+0000] {spark_submit.py:634} INFO - 24/12/09 14:05:24 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 34097.
[2024-12-09T14:05:24.921+0000] {spark_submit.py:634} INFO - 24/12/09 14:05:24 INFO NettyBlockTransferService: Server created on 2a892a3469ec:34097
[2024-12-09T14:05:24.922+0000] {spark_submit.py:634} INFO - 24/12/09 14:05:24 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2024-12-09T14:05:24.936+0000] {spark_submit.py:634} INFO - 24/12/09 14:05:24 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 2a892a3469ec, 34097, None)
[2024-12-09T14:05:24.950+0000] {spark_submit.py:634} INFO - 24/12/09 14:05:24 INFO BlockManagerMasterEndpoint: Registering block manager 2a892a3469ec:34097 with 434.4 MiB RAM, BlockManagerId(driver, 2a892a3469ec, 34097, None)
[2024-12-09T14:05:24.958+0000] {spark_submit.py:634} INFO - 24/12/09 14:05:24 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 2a892a3469ec, 34097, None)
[2024-12-09T14:05:24.960+0000] {spark_submit.py:634} INFO - 24/12/09 14:05:24 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, 2a892a3469ec, 34097, None)
[2024-12-09T14:05:25.360+0000] {spark_submit.py:634} INFO - 24/12/09 14:05:25 INFO StandaloneSchedulerBackend: SchedulerBackend is ready for scheduling beginning after reached minRegisteredResourcesRatio: 0.0
[2024-12-09T14:05:25.666+0000] {spark_submit.py:634} INFO - file_path /temp/data/test1234.csv
[2024-12-09T14:05:25.666+0000] {spark_submit.py:634} INFO - False
[2024-12-09T14:05:25.678+0000] {spark_submit.py:634} INFO - /home/***/.local/bin/python
[2024-12-09T14:05:25.682+0000] {spark_submit.py:634} INFO - ***
[2024-12-09T14:05:25.686+0000] {spark_submit.py:634} INFO - /opt/***
[2024-12-09T14:05:25.696+0000] {spark_submit.py:634} INFO - ls: cannot access '/temp/data/test1234.csv': No such file or directory
[2024-12-09T14:05:25.698+0000] {spark_submit.py:634} INFO - Traceback (most recent call last):
[2024-12-09T14:05:25.698+0000] {spark_submit.py:634} INFO - File "/opt/***/jobs/python/wordcountjob.py", line 53, in <module>
[2024-12-09T14:05:25.699+0000] {spark_submit.py:634} INFO - files = os.listdir('/temp/data/')
[2024-12-09T14:05:25.700+0000] {spark_submit.py:634} INFO - ^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-12-09T14:05:25.701+0000] {spark_submit.py:634} INFO - FileNotFoundError: [Errno 2] No such file or directory: '/temp/data/'
[2024-12-09T14:05:25.848+0000] {spark_submit.py:634} INFO - 24/12/09 14:05:25 INFO SparkContext: Invoking stop() from shutdown hook
[2024-12-09T14:05:25.851+0000] {spark_submit.py:634} INFO - 24/12/09 14:05:25 INFO SparkContext: SparkContext is stopping with exitCode 0.
[2024-12-09T14:05:25.864+0000] {spark_submit.py:634} INFO - 24/12/09 14:05:25 INFO SparkUI: Stopped Spark web UI at http://2a892a3469ec:4042
[2024-12-09T14:05:25.871+0000] {spark_submit.py:634} INFO - 24/12/09 14:05:25 INFO StandaloneSchedulerBackend: Shutting down all executors
[2024-12-09T14:05:25.875+0000] {spark_submit.py:634} INFO - 24/12/09 14:05:25 INFO StandaloneSchedulerBackend$StandaloneDriverEndpoint: Asking each executor to shut down
[2024-12-09T14:05:25.905+0000] {spark_submit.py:634} INFO - 24/12/09 14:05:25 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
[2024-12-09T14:05:25.924+0000] {spark_submit.py:634} INFO - 24/12/09 14:05:25 INFO MemoryStore: MemoryStore cleared
[2024-12-09T14:05:25.927+0000] {spark_submit.py:634} INFO - 24/12/09 14:05:25 INFO BlockManager: BlockManager stopped
[2024-12-09T14:05:25.936+0000] {spark_submit.py:634} INFO - 24/12/09 14:05:25 INFO BlockManagerMaster: BlockManagerMaster stopped
[2024-12-09T14:05:25.942+0000] {spark_submit.py:634} INFO - 24/12/09 14:05:25 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
[2024-12-09T14:05:25.977+0000] {spark_submit.py:634} INFO - 24/12/09 14:05:25 INFO SparkContext: Successfully stopped SparkContext
[2024-12-09T14:05:25.978+0000] {spark_submit.py:634} INFO - 24/12/09 14:05:25 INFO ShutdownHookManager: Shutdown hook called
[2024-12-09T14:05:25.978+0000] {spark_submit.py:634} INFO - 24/12/09 14:05:25 INFO ShutdownHookManager: Deleting directory /tmp/spark-184c64a2-9bc0-49b7-bda8-bc8c17b7da0c/pyspark-f12b03a0-1cf4-4fd9-b7e7-c7a57b474bce
[2024-12-09T14:05:25.990+0000] {spark_submit.py:634} INFO - 24/12/09 14:05:25 INFO ShutdownHookManager: Deleting directory /tmp/spark-98e9aad1-a3fa-4d06-8087-5b7387a88041
[2024-12-09T14:05:25.995+0000] {spark_submit.py:634} INFO - 24/12/09 14:05:25 INFO ShutdownHookManager: Deleting directory /tmp/spark-184c64a2-9bc0-49b7-bda8-bc8c17b7da0c
[2024-12-09T14:05:26.072+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 176, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 560, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://sparkingflow-spark-master-1:7077 --name arrow-spark --deploy-mode client jobs/python/wordcountjob.py. Error code is: 1.
[2024-12-09T14:05:26.088+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=sparking_flow, task_id=python_job, run_id=manual__2024-12-09T14:05:12.986891+00:00, execution_date=20241209T140512, start_date=20241209T140515, end_date=20241209T140526
[2024-12-09T14:05:26.116+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-09T14:05:26.118+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 484 for task python_job (Cannot execute: spark-submit --master spark://sparkingflow-spark-master-1:7077 --name arrow-spark --deploy-mode client jobs/python/wordcountjob.py. Error code is: 1.; 697)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 176, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 560, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://sparkingflow-spark-master-1:7077 --name arrow-spark --deploy-mode client jobs/python/wordcountjob.py. Error code is: 1.
[2024-12-09T14:05:26.158+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-12-09T14:05:26.194+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-09T14:05:26.199+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
